version: "3.7"

services:
    chibisafe:
        container_name: chibisafe
        build:
            context: ../
            dockerfile: ./docker/chibisafe/Dockerfile
        expose:
            - "5000"
            - "5001"
        ports:
            - "5000:5000"
        restart: unless-stopped
        hostname: chibisafe
        volumes:
            - /nas-storage/safe/storage:/usr/chibisafe/uploads
            - /nas-storage/safe/database:/usr/chibisafe/database
        environment:
            CHUNK_SIZE: 90
            ROUTE_PREFIX: /api
            RATE_LIMIT_WINDOW: 2
            RATE_LIMIT_MAX: 5
            BLOCKED_EXTENSIONS: ".jar,.exe,.msi,.com,.bat,.cmd,.scr,.ps1,.sh"
            UPLOAD_FOLDER: uploads
            SECRET: "wowfcgMHqZHwOIMLadWrKu3liyqPOOILpDLSDvuxq3YGhJmiZXJCVpnF96l11WfR"
            MAX_LINKS_PER_ALBUM: 5
            META_THEME_COLOR: "#20222b"
            META_DESCRIPTION: "Blazing fast file uploader and bunker written in node! 🚀"
            META_KEYWORDS: "chibisafe,upload,uploader,file,vue,images,ssr,file uploader,free"
            META_TWITTER_HANDLE: ""
            SERVER_PORT: 5000
            WEBSITE_PORT: 5001
            DOMAIN: "https://safe.afsa.se"
            SERVICE_NAME: Borpa
            MAX_SIZE: 20000
            GENERATE_THUMBNAILS: "true"
            GENERATE_ZIPS: "true"
            STRIP_EXIF: "true"
            SERVE_WITH_NODE: "true"
            GENERATED_FILENAME_LENGTH: 6
            GENERATED_ALBUM_LENGTH: 4
            PUBLIC_MODE: "false"
            USER_ACCOUNTS: "false"
            ADMIN_ACCOUNT: "admin"
            ADMIN_PASSWORD: "admin"
            DB_CLIENT: "sqlite3"
            DB_HOST: ""
            DB_USER: ""
            DB_PASSWORD: ""
            DB_DATABASE: ""
