version: "3.7"

services:
    chibisafe:
        container_name: chibisafe
        build:
            context: ../
            dockerfile: ./docker/chibisafe/Dockerfile
        ports:
            - "127.0.0.1:5000:5000"
        restart: unless-stopped
        hostname: chibisafe
        volumes:
            - /nas-storage/safe/storage:/usr/chibisafe/uploads
            - /nas-storage/safe/database:/usr/chibisafe/database
        environment:
            OVERWRITE_SETTINGS: "false"
            CHUNK_SIZE: 90
            ROUTE_PREFIX: /api
            RATE_LIMIT_WINDOW: 2
            RATE_LIMIT_MAX: 5
            BLOCKED_EXTENSIONS: ".jar,.exe,.msi,.com,.bat,.cmd,.scr,.ps1,.sh"
            SECRET: ""
            META_THEME_COLOR: "#20222b"
            META_DESCRIPTION: "Borpa"
            META_KEYWORDS: "chibisafe,upload,uploader,file,vue,images,ssr,file uploader,free"
            META_TWITTER_HANDLE: ""
            SERVER_PORT: 5000
            DOMAIN: "https://uwu.nu"
            SERVICE_NAME: Borpa
            MAX_SIZE: 30000
            GENERATE_THUMBNAILS: "true"
            GENERATE_ZIPS: "true"
            STRIP_EXIF: "true"
            SERVE_WITH_NODE: "true"
            GENERATED_FILENAME_LENGTH: 6
            GENERATED_ALBUM_LENGTH: 4
            PUBLIC_MODE: "false"
            USER_ACCOUNTS: "false"
            ADMIN_ACCOUNT: ""
            ADMIN_PASSWORD: ""
            DB_CLIENT: "sqlite3"
            DB_HOST: ""
            DB_USER: ""
            DB_PASSWORD: ""
            DB_DATABASE: ""
